### ISSUE TITLE
Use python logging instead of print

### ISSUE THREAD

**Issue by m-vdb** [xplenty/xplenty.py#6]
Hi there,

In case you haver time to tackle that, would be great if we could use python logging instead of plain `print`.

Thanks

Maxime.

**Comment by motymichaely** [comment]
@m-vdb - This issue was also closed by replacing print statements, correct?

**Comment by m-vdb** [comment]
yep :)

**Comment by m-vdb** [comment]
it's actually a duplicate of https://github.com/xplenty/xplenty.py/issues/7
