### ISSUE TITLE
Can you do a release on Pypi ?

### ISSUE THREAD

**Issue by m-vdb** [xplenty/xplenty.py#9]
Thanks :)

**Comment by m-vdb** [comment]
@motymichaely I understand for the tests. Can we have minimal coverage and later add more tests? It's very useful to have it as a pypi package. If you agree, I'll write a few tests, but I don't have much time right now (it's gonna be after the holidays I guess)

**Comment by motymichaely** [comment]
@m-vdb - No worries. We are going to add the required tests and support Pypi package. Follow the repo status for this.

**Comment by motymichaely** [comment]
@m-vdb - We've released xplenty.py package to Pypi.
